# Best job.

- type: job
  id: ChiefMedicalOfficer
  name: job-name-cmo
  description: job-description-cmo
  playTimeTracker: JobChiefMedicalOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 10800 #3 hrs
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 18000 #5 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 28800 # 8 hrs
  weight: 10
  startingGear: CMOGear
  icon: "ChiefMedicalOfficer"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer

- type: startingGear
  id: CMOGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCMO
    back: ClothingBackpackCMOFilled
    shoes: ClothingShoesColorBrown
    outerClothing: ClothingOuterCoatLabCmo
    id: CMOPDA
    ears: ClothingHeadsetCMO
    belt: ClothingBeltMedicalFilled
  innerclothingskirt: ClothingUniformJumpskirtCMO
  satchel: ClothingBackpackSatchelCMOFilled
  duffelbag: ClothingBackpackDuffelCMOFilled
