- type: job
  id: SecurityCadet
  name: job-name-cadet
  description: job-description-cadet
  playTimeTracker: JobSecurityCadet
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 7200 #2 hrs
    - !type:DepartmentTimeRequirement
      department: Science
      time: 7200 #2 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 7200 #2 hrs
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 7200 #2 hrs
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 7200 #2 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 21600 #6 hrs
      inverted: true # stop playing intern if you're good at security!
  startingGear: SecurityCadetGear
  icon: "SecurityCadet"
  supervisors: job-supervisors-security
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance

- type: startingGear
  id: SecurityCadetGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorRed
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsCombatFilled
    outerClothing: ClothingOuterArmorBasic
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
    pocket1: WeaponPistolMk58Nonlethal
  innerclothingskirt: ClothingUniformJumpskirtColorRed
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
